version: '3'

services:
  robot:
    build: ./
    volumes:
      - ./share:/home/survey:ro
      - ./xinetd:/etc/xinetd.d/survey:ro
    cap_add:
      - SYS_PTRACE
    ports:
      - "30201:10101"
    expose:
      - "10101"
